config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                            Controller#Action
#                 teaspoon        /teaspoon                              Teaspoon::Engine
# search_admin_credentials GET    /admin/credentials/search(.:format)    admin/credentials#search
#        admin_credentials GET    /admin/credentials(.:format)           admin/credentials#index
#                          POST   /admin/credentials(.:format)           admin/credentials#create
#     new_admin_credential GET    /admin/credentials/new(.:format)       admin/credentials#new
#    edit_admin_credential GET    /admin/credentials/:id/edit(.:format)  admin/credentials#edit
#         admin_credential GET    /admin/credentials/:id(.:format)       admin/credentials#show
#                          PATCH  /admin/credentials/:id(.:format)       admin/credentials#update
#                          PUT    /admin/credentials/:id(.:format)       admin/credentials#update
#                          DELETE /admin/credentials/:id(.:format)       admin/credentials#destroy
#          admin_resources GET    /admin/resources(.:format)             admin/resources#index
#                          POST   /admin/resources(.:format)             admin/resources#create
#       new_admin_resource GET    /admin/resources/new(.:format)         admin/resources#new
#      edit_admin_resource GET    /admin/resources/:id/edit(.:format)    admin/resources#edit
#           admin_resource GET    /admin/resources/:id(.:format)         admin/resources#show
#                          PATCH  /admin/resources/:id(.:format)         admin/resources#update
#                          PUT    /admin/resources/:id(.:format)         admin/resources#update
#                          DELETE /admin/resources/:id(.:format)         admin/resources#destroy
#               magic_lamp        /magic_lamp                            MagicLamp::Engine
#             sessions_new GET    /sessions/new(.:format)                sessions#new
#                     root GET    /                                      static_pages#home
#                   signup GET    /signup(.:format)                      users#new
#                          POST   /signup(.:format)                      users#create
#                    about GET    /about(.:format)                       static_pages#about
#                     help GET    /help(.:format)                        static_pages#help
#                     news GET    /news(.:format)                        static_pages#news
#                    login GET    /login(.:format)                       sessions#new
#                          POST   /login(.:format)                       sessions#create
#                   logout DELETE /logout(.:format)                      sessions#destroy
#                    users GET    /users(.:format)                       users#index
#                          POST   /users(.:format)                       users#create
#                 new_user GET    /users/new(.:format)                   users#new
#                edit_user GET    /users/:id/edit(.:format)              users#edit
#                     user GET    /users/:id(.:format)                   users#show
#                          PATCH  /users/:id(.:format)                   users#update
#                          PUT    /users/:id(.:format)                   users#update
#                          DELETE /users/:id(.:format)                   users#destroy
#  resource_storage_arrays GET    /resource/storage/arrays(.:format)     resource/storage/arrays#index
#   resource_storage_array GET    /resource/storage/arrays/:id(.:format) resource/storage/arrays#show
#
# Routes for Teaspoon::Engine:
#    root GET  /                             teaspoon/suite#index
# fixture GET  /fixtures/*filename(.:format) teaspoon/suite#fixtures
#   suite GET  /:suite(.:format)             teaspoon/suite#show {:defaults=>{:suite=>"default"}}
#         POST /:suite/:hook(.:format)       teaspoon/suite#hook {:defaults=>{:suite=>"default", :hook=>"default"}}
#
# Routes for MagicLamp::Engine:
#   root GET  /                magic_lamp/fixtures#index
#   lint GET  /lint(.:format)  magic_lamp/lint#index
#        GET  /*name(.:format) magic_lamp/fixtures#show
#

Rails.application.routes.draw do
  
  namespace :admin do
    resources :credentials do
      collection do
        get "search"
      end
    end
    resources :resources
  end
  
  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)
  
  get 'sessions/new'

  root 'static_pages#home'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/news', to: 'static_pages#news'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :bears_instances, only: [:index]
  namespace :resource do
    namespace :storage do
      resources :arrays, only: [:index, :show]
    end
  end
end

app/views/layouts/_headline.html.erb
<% if content_for?(:title) && !content_for?(:no_headline)%>
<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header"><%= yield :title %></h3>
	</div>
</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom:0px">
  <div class="navbar-header">
  	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
  		<span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <%= link_to BEARS['app_name'], root_path, id: "logo", class: "navbar-brand" %>
  </div>
  <ul class="nav navbar-top-links navbar-right">
      <li class="dropdown">
      	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
        	<i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
        	<% if logged_in? %>
	        	<li>
	        		<%= link_to current_user do %>
	        			<i class="fa fa-user fa-fw"></i> User Profile
	        		<% end %>
	            </li>
	            <li>
	            	<%= link_to edit_user_path(current_user) do %>
	            		<i class="fa fa-gear fa-fw"></i> Settings
	            	<% end %>
	            </li>
	            <li class="divider"></li>
	            <li>
	            	<%= link_to logout_path, method: :delete do %>
	        			<i class="fa fa-sign-out fa-fw"></i> Logout
	        		<% end %>
	            </li>
            <% else %>
	            <li>
	            	<%= link_to login_path do %>
	        			<i class="fa fa-sign-in fa-fw"></i> Log in
	        		<% end %>
	            </li>
            <% end %>
        </ul>
      </li>
      <li class="dropdown">
      	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
        	<i class="fa fa-book fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
        	<li>
        		<%= link_to news_path do %>
        			News
        		<% end %>
            </li>
            <li>
            	<%= link_to help_path do %>
        			 Help
        		<% end %>
            </li>
            <li>
            	<%= link_to about_path do %>
        			About
        		<% end %>
            </li>
        </ul>
      </li>
  </ul>
  
  <% if logged_in? %>
	  <%= render 'layouts/sidebar' %>
   <% end %>
</nav>

app/views/layouts/_page_header.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><%= yield :title %></h1>
	</div>
</div>

app/views/layouts/_rails_default.html.erb
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<%= yield :turbolinks_cache %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_sidebar.html.erb
	  <div class="navbar-default sidebar" role="navigation">
	  	<div class="sidebar-nav navbar-collapse">
	    	<ul class="nav in" id="side-menu">
	        	<li class="sidebar-search">
	            	<div class="input-group custom-search-form">
	                	<input type="text" class="form-control" placeholder="Search...">
	                  	<span class="input-group-btn">
	                       	<button class="btn btn-default" type="button">
	                           	<i class="fa fa-search"></i>
	                        </button>
	                   </span>
	                </div>
	                <!-- /input-group -->
	            </li>
	            <li>
	            	<%= link_to root_path, id:"menu_dashboard" do %>
	            		<i class="fa fa-dashboard fa-fw"></i> Dashboard
	            	<% end %>
	            </li>
	            <li>
	            	<%= link_to "#", id:"menu_resources" do %>
	            		<i class="fa fa-cloud fa-fw"></i> Resources<span class="fa arrow"></span>
	            	<% end %>
	            	<ul class="nav nav-second-level collapse">
	                	<li>
	                    	<%= link_to "#", id:"menu_arrays" do %>
	                        	<i class="fa fa-bars fa-fw"></i> Arrays<span class="fa arrow">
	                        <% end %>
	                        <ul class="nav nav-third-level collapse">
		                    	<li>
			                    	<%= link_to resource_storage_arrays_path, id:"menu_arrays_all" do %>
			                    		<i class="fa fa-angle-right fa-fw"></i> ALL
			                    	<% end %>
			                    </li>
			                	<li>
			                		<%= link_to resource_storage_arrays_path(array_type: "A3Par"), id:"menu_arrays_3par" do %>
			                    		<i class="fa fa-angle-right fa-fw"></i> 3PAR
			                    	<% end %>
			                    </li>
			                    <li>
			                    	<%= link_to resource_storage_arrays_path(array_type: "Eva"), id:"menu_arrays_eva" do %>
			                    		<i class="fa fa-angle-right fa-fw"></i> EVA
			                    	<% end %>
			                    </li>
			                </ul>
	                    </li>
	                </ul>
	            </li>
	            <% if current_user.admin? %>
	             <li>
	                <a href="#" id="menu_configuration"><i class="fa fa-wrench fa-fw"></i> Configuration<span class="fa arrow"></span></a>
	                   <ul class="nav nav-second-level collapse">
	                      <li>
	                      	<%= link_to "#", id:"menu_discovery" do %>
	            				<i class="fa fa-eye fa-fw"></i> Discovery<span class="fa arrow"></span>
	            			<% end %>
	            			<ul class="nav nav-third-level collapse">
	            				<li>
	                         	<%= link_to admin_credentials_path, id:"menu_credentials" do %>
	                         		<i class="fa fa-bars fa-fw"></i> Credentials
	                         	<% end %>
	                         	</li>
	                         	<li>
	                         	<%= link_to admin_resources_path, id:"menu_resources_disc" do %>
	                         		<i class="fa fa-cloud fa-fw"></i> Resources
	                         	<% end %>
	                         	</li>
	                        </ul>
	                      </li>
	                      <li>
	                         <%= link_to users_path, id:"menu_users" do %>
	                         	<i class="fa fa-users fa-fw"></i> Users
	                         <% end %>
	                      </li>
	                   </ul>
	             </li>
	             <% end %>
	       </ul>
	     </div>
	     <!-- /.sidebar-collapse -->
	   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
  </head>

  <body>
  	<div id="wrapper">
      <%= render "layouts/nav" %>
      <div id="<%= wrapper_id %>">
      	<%= render "layouts/headline" %>
      	<tt-flash></tt-flash>
      	<div class="row">
      		<div class="col-md-12">
		      	<% flash.each do |message_type, message| %>
		        	<%= content_tag(:div, message, class: "row alert alert-#{message_type}") %>
		      	<% end %>
	      	</div>
      	</div>
      	<%= yield %>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>